name: Deploy

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        environment: prod
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Deploy to server
              uses: appleboy/ssh-action@v0.1.10
              with:
                host: ${{ secrets.SSH_IP }}
                username: ${{ secrets.SSH_USER }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: |
                  cd ~/Dev/gaby/gaby-shared-album-frontend

                  echo "Pulling latest code..."
                  git pull origin main

                  # Recreate .env file from GitHub Secrets
                  cat > .env <<EOF
                  REACT_APP_API_URL=${{ vars.REACT_APP_API_URL }}
                  REACT_APP_FEATURE_FLAG=${{ vars.REACT_APP_FEATURE_FLAG }}
                  EOF

                  # Run your scripts
                  bash ./scripts/deploy.sh




